/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех заявок */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список заявок */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 10 */
                            count?: number;
                            data?: components["schemas"]["Ticket"][];
                        };
                    };
                };
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Создать новую заявку */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketCreate"];
                };
            };
            responses: {
                /** @description Заявка успешно создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Ticket"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить заявку по ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID заявки */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Заявка найдена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Ticket"];
                        };
                    };
                };
                /** @description Неверный ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Обновить заявку */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID заявки */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketUpdate"];
                };
            };
            responses: {
                /** @description Заявка успешно обновлена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Ticket"];
                            /** @example Заявка успешно обновлена */
                            message?: string;
                        };
                    };
                };
                /** @description Неверные данные */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Удалить заявку */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID заявки */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Заявка успешно удалена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Заявка успешно удалена */
                            message?: string;
                        };
                    };
                };
                /** @description Неверный ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех пользователей */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список пользователей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 10 */
                            count?: number;
                            data?: components["schemas"]["User"][];
                        };
                    };
                };
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Ошибка сервера при получении пользователей */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Создать нового пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
            responses: {
                /** @description Пользователь успешно создан */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Пользователь создан */
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["UserExists"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Ошибка сервера при создании пользователя */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пользователь найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                404: components["responses"]["UserNotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Ошибка сервера при получении пользователя по id */
                            error?: string;
                        };
                    };
                };
            };
        };
        /** Обновить пользователя */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
            responses: {
                /** @description Пользователь успешно обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Пользователь обновлен */
                            message?: string;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                404: components["responses"]["UserNotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Ошибка сервера при обновлении пользователя */
                            error?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Удалить пользователя */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID пользователя */
                    id: components["parameters"]["userId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пользователь успешно удален */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Пользователь удален */
                            message?: string;
                            data?: {
                                /** @example 1 */
                                id?: number;
                            };
                        };
                    };
                };
                404: components["responses"]["UserNotFound"];
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Ошибка сервера при удалении пользователя */
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/telegram/{telegramId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по Telegram ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Telegram ID пользователя */
                    telegramId: components["parameters"]["telegramId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Пользователь найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Пользователь не найден */
                            message?: string;
                        };
                    };
                };
                /** @description Ошибка сервера */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Ошибка сервера при получении пользователя по telegram_id */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Ticket: {
            /** @example 1 */
            id?: number;
            /** @example Сантехника */
            category?: string;
            /** @example Протекает кран на кухне */
            description?: string;
            /** @example ул. Ленина, 10, кв. 25 */
            address?: string;
            /** @example open */
            status?: string;
            /** @example 123 */
            resident_id?: number;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at?: string;
        };
        TicketCreate: {
            /** @example Сантехника */
            category: string;
            /** @example Протекает кран на кухне */
            description: string;
            /** @example ул. Ленина, 10, кв. 25 */
            address?: string;
            /** @example 123 */
            resident_id: number;
        };
        TicketUpdate: {
            /** @example Сантехника */
            category?: string;
            /** @example Протекает кран на кухне */
            description?: string;
            /** @example ул. Ленина, 10, кв. 25 */
            address?: string;
            /** @example in_progress */
            status?: string;
        };
        User: {
            /** @example 1 */
            id?: number;
            /** @example Иван Иванов */
            name?: string;
            /** @example hashed_password_123 */
            password?: string;
            /** @example 123456789 */
            telegram_id?: number;
            /** @example @ivanov */
            telegram_username?: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at?: string;
        };
        UserCreate: {
            /** @example Иван Иванов */
            name: string;
            /** @example 123456789 */
            telegram_id: number;
            /** @example @ivanov */
            telegram_username?: string;
            /** @example password123 */
            password?: string;
        };
        UserUpdate: {
            /** @example Иван Иванов (обновленный) */
            name?: string;
            /** @example new_password_123 */
            password?: string;
        };
    };
    responses: {
        /** @description Ресурс не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success?: boolean;
                    /** @example Заявка не найдена */
                    error?: string;
                };
            };
        };
        /** @description Неверные параметры запроса */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success?: boolean;
                    /** @example Имя и telegram_id обязательны */
                    error?: string;
                };
            };
        };
        /** @description Пользователь не найден */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success?: boolean;
                    /** @example Пользователь не найден */
                    error?: string;
                };
            };
        };
        /** @description Пользователь уже существует */
        UserExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example false */
                    success?: boolean;
                    /** @example Пользователь с таким telegram id уже существует */
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description ID пользователя */
        userId: number;
        /** @description Telegram ID пользователя */
        telegramId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
